version: "3.9"

services:
  products_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_products:/var/lib/postgresql/data

  inventory_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5433:5432"
    volumes:
      - postgres_inventory:/var/lib/postgresql/data

  products:
    build: ./products
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./products:/app
    ports:
      - "8000:8000"
    depends_on:
      - products_db

  inventory:
    build: ./inventory
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./inventory:/app
    ports:
      - "8001:8001"
    depends_on:
      - inventory_db

volumes:
  postgres_products:
  postgres_inventory:
